### ISSUE TITLE
Getting ValueError: level must be >= 0

### ISSUE THREAD

**Issue by balandongiv** [cournape/import-profiler#9]
Thanks for the package.

May I know what is the issue for the error

`ValueError: level must be >= 0`

The code to produce the above error are

```
from import_profiler import profile_import

with profile_import() as context:
    import mne
    # from mne_features.feature_extraction import extract_features
    context.print_info ()
```
The two package can be installed

1) mne_feature
`pip install git+https://github.com/mne-tools/mne-features.git#egg=mne_features`

2) mne-python

`pip install -U https://github.com/mne-tools/mne-python/archive/main.zip`

**Comment by prashantsengar-cl** [comment]
It looks like an issue because the profiler does not support Python 3. 
You can use https://github.com/prashantsengar-cl/import-profiler
